// Date: 13.02.2015 15:09:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.konatatatata.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class mine extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer shorta;
    ModelRenderer shortb;
    ModelRenderer shortc;
    ModelRenderer shortd;
    ModelRenderer tip;
  
  public mine()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 6, 2, 6);
      base.setRotationPoint(-3F, 22F, -3F);
      base.setTextureSize(32, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      shorta = new ModelRenderer(this, 0, 0);
      shorta.addBox(0F, 0F, 0F, 1, 2, 4);
      shorta.setRotationPoint(-4F, 22F, -2F);
      shorta.setTextureSize(32, 32);
      shorta.mirror = true;
      setRotation(shorta, 0F, 0F, 0F);
      shortb = new ModelRenderer(this, 0, 0);
      shortb.addBox(0F, 0F, 0F, 1, 2, 4);
      shortb.setRotationPoint(3F, 22F, -2F);
      shortb.setTextureSize(32, 32);
      shortb.mirror = true;
      setRotation(shortb, 0F, 0F, 0F);
      shortc = new ModelRenderer(this, 0, 0);
      shortc.addBox(0F, 0F, 0F, 4, 2, 1);
      shortc.setRotationPoint(-2F, 22F, 3F);
      shortc.setTextureSize(32, 32);
      shortc.mirror = true;
      setRotation(shortc, 0F, 0F, 0F);
      shortd = new ModelRenderer(this, 0, 0);
      shortd.addBox(0F, 0F, 0F, 4, 2, 1);
      shortd.setRotationPoint(-2F, 22F, -4F);
      shortd.setTextureSize(32, 32);
      shortd.mirror = true;
      setRotation(shortd, 0F, 0F, 0F);
      tip = new ModelRenderer(this, 0, 0);
      tip.addBox(0F, 0F, 0F, 2, 1, 2);
      tip.setRotationPoint(-1F, 21F, -1F);
      tip.setTextureSize(32, 32);
      tip.mirror = true;
      setRotation(tip, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    shorta.render(f5);
    shortb.render(f5);
    shortc.render(f5);
    shortd.render(f5);
    tip.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
